### ISSUE TITLE
April 14 morning review

### ISSUE THREAD

**Issue by emasdev** [SigmaSam/PositioningandFloatingElementsGabriel-Samuel#1]
Please comment if you see any issue or improvement

**Comment by asiimwedismas** [comment]
You are miss using <section>. Looks to me like u replaced div with section

**Comment by emasdev** [comment]
Try to avoid negative values for margins

**Comment by shubhsk88** [comment]
# Issues in HTML

- Use Proper Semantics 
- Try using classes instead of ID
-  write all the name of classes in lowercase 
-  Use a proper name for the classes so it is easy to know which part are you trying to work on

# Issues in CSS

- Use Border-Box model 
- avoid Giving negative margin
