### ISSUE TITLE
April 21 morning review

### ISSUE THREAD

**Issue by thedekerone** [SigmaSam/PositioningandFloatingElementsGabriel-Samuel#3]
Please comment if you see any issue or improvement

**Comment by emasdev** [comment]
Whenever you use a section tag you need to have headings inside

https://www.lifewire.com/html5-section-element-3467994

**Comment by asiimwedismas** [comment]
If you don't have any meaningful heading to put in the section, just include a heading tag and set its display to none

**Comment by shubhsk88** [comment]
- Use header tag with article tag
- Use the p tag instead of using break tags
- Use CSS style instead of using a strong tag 
- Add the anchor tag in icon 
- Use CSS styling for defining image and iframe width 
-
